"""
Build standalone ArchipelagoSSHDPatcher.exe using PyInstaller.

This bundles Python, PyQt6 (for the GUI), and all patcher dependencies into a
single exe file so end users don't need Python installed.

Usage:
    pip install pyinstaller   (one-time, developer only)
    python build_patcher_exe.py
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path


def build_patcher_exe():
    """Build the standalone SSHD Archipelago Patcher executable."""

    source_dir = Path(__file__).parent
    dist_dir = source_dir / "dist"
    exe_name = "ArchipelagoSSHDPatcher"
    spec_path = source_dir / f"{exe_name}.spec"

    print("=" * 60)
    print("  Building ArchipelagoSSHDPatcher.exe (single file)")
    print("=" * 60)
    print()

    # ── Verify dependencies ───────────────────────────────────────
    try:
        import PyInstaller
        print(f"[OK] PyInstaller {PyInstaller.__version__}")
    except ImportError:
        print("[!] PyInstaller not found. Installing...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "pyinstaller"])
        import PyInstaller
        print(f"[OK] PyInstaller {PyInstaller.__version__} installed")

    required = {
        "yaml": "pyyaml",
        "PyQt6": "PyQt6",
        "platformdirs": "platformdirs",
    }
    for mod, pip_name in required.items():
        try:
            __import__(mod)
            print(f"[OK] {mod}")
        except ImportError:
            print(f"[!] Missing: {mod}  (pip install {pip_name})")
            sys.exit(1)

    print()

    # ── Resolve paths for the .spec file ──────────────────────────
    datas_lines = []

    # SSHD world modules the patcher imports at runtime
    sshd_files = [
        "Locations.py", "Items.py", "SSHD_Options.py",
        "platform_utils.py", "setting_string_decoder.py",
        "SSHDRWrapper.py", "archipelago.json",
    ]
    for f in sshd_files:
        p = source_dir / f
        if p.exists():
            datas_lines.append(f"    (r'{p}', '.'),")

    # rando/ package (ArcPatcher etc.)
    rando_dir = source_dir / "rando"
    if rando_dir.exists():
        for f in rando_dir.glob("*.py"):
            datas_lines.append(f"    (r'{f}', 'rando'),")

    # assets/ directory (logos, templates)
    assets_dir = source_dir / "assets"
    if assets_dir.exists():
        for f in assets_dir.rglob("*"):
            if f.is_file():
                rel = f.relative_to(assets_dir)
                dest = f"assets/{rel.parent.as_posix()}" if rel.parent != Path(".") else "assets"
                datas_lines.append(f"    (r'{f}', '{dest}'),")

    # sshd-rando-backend — the entire backend tree (logic, patches, data, etc.)
    backend_dir = source_dir / "sshd-rando-backend"
    if backend_dir.exists():
        for f in backend_dir.rglob("*"):
            if f.is_file() and "__pycache__" not in str(f):
                rel = f.relative_to(backend_dir)
                dest = f"sshd-rando-backend/{rel.parent.as_posix()}" if rel.parent != Path(".") else "sshd-rando-backend"
                datas_lines.append(f"    (r'{f}', '{dest}'),")
        print(f"[OK] sshd-rando-backend bundled")
    else:
        print("[WARN] sshd-rando-backend directory not found!")

    datas_block = "\n".join(datas_lines)

    # ── Generate .spec file ───────────────────────────────────────
    spec_content = f"""\
# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_patcher_exe.py — do not edit manually.

block_cipher = None

datas = [
{datas_block}
]

hiddenimports = [
    'yaml',
    'platformdirs',
    'colorama',
    'typing_extensions',
    'PyQt6', 'PyQt6.QtCore', 'PyQt6.QtWidgets', 'PyQt6.QtGui',
    'PyQt6.sip',
]

excludes = [
    'matplotlib', 'numpy', 'pandas', 'scipy', 'tkinter',
    'test', 'setuptools', 'pip', 'wheel',
    'docutils', 'pygments',
    'kivy', 'kivymd',
    'pymem', 'websockets', 'psutil',
    'PySide6', 'PySide2', 'PyQt5',
]

a = Analysis(
    [r'{source_dir / "SSHDPatcher.py"}'],
    pathex=[r'{source_dir}'],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='{exe_name}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    console=True,
)
"""

    spec_path.write_text(spec_content, encoding="utf-8")
    print(f"[OK] Generated spec: {spec_path}")
    print()

    # ── Run PyInstaller ───────────────────────────────────────────
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",
        "--clean",
        "--log-level", "WARN",
        str(spec_path),
    ]

    print("Running PyInstaller...")
    print()

    # Prevent Kivy from initialising OpenGL if it happens to be installed.
    # On headless CI runners Kivy's GL check calls sys.exit(), killing the
    # PyInstaller process.  These env vars suppress that behaviour.
    env = os.environ.copy()
    env["KIVY_DOC_INCLUDE"] = "1"
    env["KIVY_NO_ARGS"] = "1"
    env["KIVY_NO_CONSOLELOG"] = "1"
    env["KIVY_NO_FILELOG"] = "1"

    result = subprocess.run(cmd, cwd=str(source_dir), env=env)

    if result.returncode != 0:
        print()
        print("[FAIL] PyInstaller build failed!")
        sys.exit(1)

    # ── Verify output ─────────────────────────────────────────────
    exe_path = dist_dir / f"{exe_name}.exe"
    if not exe_path.exists():
        exe_path = dist_dir / exe_name  # non-Windows

    if not exe_path.exists():
        print(f"[FAIL] Executable not found at {exe_path}")
        sys.exit(1)

    size_mb = exe_path.stat().st_size / (1024 * 1024)

    print()
    print("=" * 60)
    print(f"[OK] Built successfully!")
    print(f"     Exe: {exe_path} ({size_mb:.1f} MB)")
    print("=" * 60)

    return exe_path


if __name__ == "__main__":
    build_patcher_exe()
